kind: pipeline
name: production

clone:
  git:
    image: plugins/git
    pull: true

steps:
  - name: build
    image: node
    commands:
      - npm install
      - export GATSBY_TELEMETRY_DISABLED=1
      - export NODE_ENV=production
      - npm run build

  - name: deploy
    image: drillster/drone-rsync
    settings:
      hosts:
        from_secret: deploy_host
      port:
        from_secret: deploy_port
      user:
        from_secret: deploy_user
      key:
        from_secret: deploy_key
      target:
        from_secret: deploy_target
      source:  /drone/src/public/
      recursive: true
      delete: true
      exclude:
        - "README.md"
