# Site settings
title:          Erik Samuelsson
description:    "Blog and homepage of web developer Erik Samuelsson - A front-end ninja that loves all pixels equally."
url:            "https://eriksamuelsson.com"

# Google Analytics
google_analytics: UA-128484791-1

# Author
author:
  name:         Erik Samuelsson
  url:          https://eriksamuelsson.com
  email:        hello@eriksamuelsson.com

twitter:
  username: ErikSamuelsson
  card: summary

# Build settings
markdown:       kramdown
include:
  - _pages

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-archives

# Permalinks
permalink:      /:year/:month/:day/:title/
paginate:       10

# Archive
jekyll-archives:
  enabled: 'all'
  layouts:
    year: 'archive-year'
    month: 'archive-month'
    day: 'archive-day'
    tag: 'archive-tag'
  permalinks:
    year: '/:year/'
    month: '/:year/:month/'
    day: '/:year/:month/:day/'
    tag: '/tag/:name/'
